### ISSUE TITLE
Value of MOOD in etc/erg.smi should be mood and not bool

### ISSUE THREAD

**Issue by goodmami** [delph-in/erg#12]
Here is the variables section of `etc/erg.smi`:

```
variables:

  u.
  i < u.
  p < u.
  h < p.
  e < i : SF sf, TENSE tense, MOOD bool, PROG bool, PERF bool.
  x < i & p : PERS person, NUM number, GEND gender, IND bool, PT pt.
```

The value of `MOOD` on `e` should be `mood` and not `bool`. This was discussed and agreed upon in email but it appears to not be committed to the repository (http://svn.delph-in.net/erg/trunk). Most of the other bugs discussed were fixed and committed.

**Comment by danflick** [comment]
Indeed, for some reason I have not yet committed that change to the trunk repository, even though I corrected it locally ages ago.  I'll be sure it makes it into the repository along with other more recent changes.

**Comment by goodmami** [comment]
@danflick I see the update in the 2018 tagged version but still not in the trunk version. I'm just pinging you to make sure the 2019 version includes the change.

**Comment by oepen** [comment]
the current trunk looks fine, in this regard.
